dist: xenial

addons:
    apt:
        packages:
            - ant-optional

language: php

php:
    - "5.6"

matrix:
    exclude:

before_script:
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer self-update && composer --version
    - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
    depth: 2147483647

cache:
    directories:
        - vendor
